### PR TITLE
Redesign 2021 - Simple

### PR DESCRIPTION
**Pull request by TomasVotruba**
- closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1169
- closes https://github.com/TomasVotruba/tomasvotruba.com/issues/851
- closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1178
- closes https://github.com/TomasVotruba/tomasvotruba.com/issues/1203

<br>

Inspiration - https://github.com/TomasVotruba/tomasvotruba.com/issues/835

<br>

# What changes in Content?

- cleaning lady list dropped, the http://rectorclick.com/ by @rectorphp is comming instead
- homepage is now welcome text 
- blog archive moved to blog
- clusters were dropped, to focus on clear known terms of - posts vs books - kept the most used one for incoming visitors, [Monorepo from Hero to Zero](https://tomasvotruba.com/cluster/monorepo-from-zero-to-hero/)
- remove tested posts to keep content simple, leave the quality assurance to books 

<br>

# What changes in Design?

- remove font-awesome - too heav for 10 icons the website used - use couple of emojis where needed instead
- less fancy colors, more focus on content
- dropped search, google is good enough and has much more features :)
- dropped dynamic mobile/pc menu, keep it simple and practical
- dropped jquery
- show deprecated posts with warning, to share the experience fuckups :)
- show updated posts with colors

### CODE REVIEW

**Comment by TomasVotruba** [comment]
First shapes... :) 

image

**Comment by TomasVotruba** [comment]
Let's see if this version can beta current PageSpeed :)

**Comment by TomasVotruba** [comment]
## Almost There...

PHP-Trainings-Rectoring-and-Posts-Tomas-Votruba

**Comment by TomasVotruba** [comment]
## From 91 to 96... :tada: 



image

**Comment by staabm** [comment]
Looks great. Good job 👏

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
