### PR TITLE
Update 2020-07-16-10-cool-features-you-get-after-switching-from-yaml-to-php-configs.md

### PR DESCRIPTION
**Pull request by vrbata**
Hi Tomáš,
another week another article, nice :)

Sending you few improvements and one question.

php configuration is standard in Laravel and in most cases and it feels better then yaml/xml so I am glad we will see it in Symfony in the future too. Both PHPStan and Rector provide a lot of additional control over our codebases as you described, but what do you think about the future of templates? These days I think almost all of us are using twig, but I feel with the growing benefits of AST should we switch templates to php too? Or do you think new tools similar to PHPStan and Rector will be created just for templates control? Or there will be plugins to those existing tools scanning already compiled twig templates but reporting us the correct file and line like we are used to from javascript transpilers? Or do you see another way how to improve strictness of templates?

Thank you as always :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi Pepa,

just logged in after 2 hours :D what a chance :tada: 

Future of templates? That's very interesting question. From what I see in companies I work with, most of them shift towards Javascripts. Websites now have to mobile app and also watch app at the same time. I think that PHP/Twig technology is not a right language for such features.

Switching templates to PHP brings only value in easier maintenance and development, but rather slows down business (there is no ajax in PHP, not mobile native/web progressive app).

I think the next step evolution happens when 2 conditions meet at the same time:

- the development/maintanence of code improves rapidly
- the business gains value 

<br>

But I don't work with much templates on daily basis, mostly API + Javascript front end, so I'm not sure I'm the right person to answer, since I lack practical experience.

What do you think from your own practise?

**Comment by vrbata** [comment]
Yes, that was a very quick merge :D

From my point of view when we are building e-commerce sites, not applications, SEO is a huge part we have to consider when rendering some html to the browser as there is a ton of metrics to be considered.
I think in our company we have very mature technology stack for writing PHP code, but we lack the same maturity for javascript world, we only enhance parts of the application with javascript as we don't have the knowledge how to write high maintainable javascript code as we do for php with the same or higher effectivity (design patterns, tests, automatization - phpstan, rector etc.)
So for us writing e-commerce sites as API + js would be much slower and much more expensive than now.
I think in our sort of business it's very common to render all on the server in the same technology.
But I get your point that for pure web applications, javascript is better because of reasons you mentioned - native/web progressive apps which are more interactive and engaging.

Now it's sometimes pain as we can rector our entities and data objects in no time. But then we have to wait till all end-to-end tests are green to find out the impact on our templates. So some sort of faster automatic control would be nice time to time :)

**Comment by TomasVotruba** [comment]
I see. If you take into account your history and your context, it makes sense to stick mostly with PHP. 

I'm trying to look at a bigger picture, outside my work scope, and if I was 10 and starting coding, I'd pick Javascript, since it has much bigger space to improve. If there is a space for improvements, it's a matter of time some entity - human or comapny - will take that space.

I mean writing RectorJS to usable level is matter of 3-6 months. Path in PHP is clear and trampled, so port is matter of time. Same as JUnit and PHPUnit in the past.

But I don't know JS community at all, how they work, cooperate, what are they like.


In most cases, devs usually end-up in deep love with language they had first very good sex at young age. And mine was PHP :)

**Comment by vrbata** [comment]
> In most cases, devs usually end-up in deep love with language they had first very good sex at young age. And mine was PHP :)

Totally agree, same for me :) When a new version of php comes I already know what to expect, already want to try and use new features and BC breaks are just small rocks on the road rector can handle, so I always love when new php is installed to our servers.

But if I compare it with nodejs that we use for some frontend build precesses its always like hmmm my linux installed new version of nodejs - and then after few minutes - wtf are those "idiots" doing, nothing is working now from our build process I have to revert my nodejs version then :D

I would like to be better at javascript and would like to understand the whole ecosystem as I understand php world, but if I take into account that learning php to the level I am today took me a few thousands hours outside of school and work - basically 8 hours in work and another 3 hours every day for learning for around 2 years, after that I slowed a bit :) then I don't want to invest same amount of time to another language.

Thank you for your insight!

**Pull request merged**
