### PR TITLE
Improvements to wording, fixes of typos

### PR DESCRIPTION
**Pull request by honzajavorek**
Hi 👋 Thank you for a great article, I enjoyed it! I spotted a few weak spots in the writing, and I thought I could contribute to your blog by sending this PR proposing a few improvements. Keep up the good work, happy coding to you too!

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Oioi, nice job :+1:

**Comment by TomasVotruba** [comment]
Thank you! Happy quarantine!

Btw, Coffee Karlin is opened :P

**Comment by honzajavorek** [comment]
Haha, it is! But [I have supplies](https://www.facebook.com/honzajavorek/posts/10157897264842707?notif_id=1584270998183158)!

**Comment by TomasVotruba** [comment]
Content not found :D

**Pull request merged**
