### PR TITLE
Fix dead links

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
One question regarding the article over all: can symplify in combination with the phpstan rules only check the calisthenics rules? Or can the rules also be enforced using the `—fix` switch?

**Comment by TomasVotruba** [comment]
Thanks!

I'm not sure what you mean by "combination". What is the goal exactly?

**Comment by TomasVotruba** [comment]
To check calisthenics rules only, this config must be included in `phpstan.neon`:
https://github.com/symplify/phpstan-rules/blob/master/packages/object-calisthenics/config/object-calisthenics-rules.neon

**Comment by staabm** [comment]
My question in a nutshell:
- can symplify fix code regarding calisthenics rules? Or is it just checking and I need to fix manually?

**Comment by TomasVotruba** [comment]
Oh, I see. It's PHPStan, so it can only report (read-only).

Luckily, few of those rules are partially implemented in @rectorphp :

- `NoElseAndElseIfRule` → `SetList::EARLY_RETURN`
- `NoChainMethodCallRule` → `SetList::DEFLUENT`
- short name rules →  `SetList::NAMING` - mostly type based

**Pull request merged**
