### PR TITLE
Update 2020-06-29-how-will-programming-look-like-in-2025.md

### PR DESCRIPTION
**Pull request by vrbata**
Hi Tomáš,

Thanks for your blog post, really interesting opinion I would like to see as the future too :) Mainly I would like to see `open-source developer will become a new full-time position`. I regognize `AST` as powerfull tool to be aware of and be able to use it, but your ideas are next level I didn't think of - very cool.

Thanks  for that :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi Pepa,

thanks for fixes and specific feedback!
Well, would you like to work as an open-source developer? I have small position opened for Rector ;)

As for AST, I've noticed you're working on some advanced PHPStan rules. Great way to grow :+1: 

What are your dreams that future should not miss?

**Comment by vrbata** [comment]
I think as open-source developer as you described, you have limitless posbilities. Today you work fulltime for some company in ideal world you have some dedicated time for learning new stuff or for experimenting with existing codebase decreasing technical debt with new tools, but I think this is not as standard as I would like it to be. So you have to learn in your free time mainly for free (reading, contributing to OS projects etc.) and this can be barrier for so many people bacause of familly needs your attention, you will rather work overtimes to have more money... but if you would be paid for your contributing (learning) its win for everybody. There is a lot of benefits on my mind with this model I cant write about as this would be reading X hours long :)

Yes i like power of AST and mindset behind it. On our old platform I can't imagine any bigger refactoring without spending month on it with questinable result (no tests, no rector, no nothing). Now on our new platform I start on friday with some refactoring I finish it on sunday. On monday on stand-up I just say btw I refactored 4k files out of 7k. I automerged it as you dont want to code review it and it's already on 2 production sites no big deal :)

It also changed my perspective on testing. In past I just said to myself hmmm what this test should look like so me and my team could say it's working correctly. These days my question is hmmm what tests do I have to write so I can rector 5k lines on friday night in one go and be sure nothing got broken.

Lastly our famous question from our boss you will hear multiple times per second: Do you have it already?
My team always say: You know I had it it was working but Josef did code review and I have to write those tests, this rename, this separate and now it's not working and I need X hours do make those changes :D 
I could buy popcorn on my way to work sit behind my devs and ask them as usual multiple times per second: What are you doing right now? :D OR I can write some rector/phpstan rules so I don't have to :)

Anyway this could be even longer and I would like to continue in this conversation on this topic. So maybe another time in person :)

Take care!

**Comment by TomasVotruba** [comment]
> On monday on stand-up I just say btw I refactored 4k files out of 7k. I automerged it as you dont want to code review it and it's already on 2 production sites no big deal :)

:laughing: :partying_face: That's epic man!

>  These days my question is hmmm what tests do I have to write so I can rector 5k lines on friday night in one go and be sure nothing got broken.

That's very good point, I have never realized that, but it's true :+1: 

> but Josef did code review and I have to write those tests, this rename, this separate and now it's not working and I need X hours do make those changes :D

You know that's a sign of review smell (as in *code smell*) and should write Rector/PHPStan rule for that? I help companies to improve exactly such tedius process, because it's waste of your time, was of their time and it's a work that machine should do.

> OR I can write some rector/phpstan rules so I don't have to :)

The question is, why haven't you done that already? :) 

> Anyway this could be even longer and I would like to continue in this conversation on this topic. So maybe another time in person :)

If it can be automated, I automate it ;) 

<br>

I really wish you'd write about these thoughs, as your comments always bring some new view points on my daily work that I can learn from and benefit for the rest of my life. And I think I would not be the only one ;)

**Comment by vrbata** [comment]
> You know that's a sign of review smell (as in code smell) and should write Rector/PHPStan rule for that? I help companies to improve exactly such tedius process, because it's waste of your time, was of their time and it's a work that machine should do.

Yes I totally agree, that was the reason I started to write rector/phpstan rules for us to save time, because that situation I wrote about.

> I really wish you'd write about these thoughs, as your comments always bring some new view points on my daily work that I can learn from and benefit for the rest of my life. And I think I would not be the only one ;)

I very much  appreciate that but  you know me I don't enjoy much public attention and I don't feel confortable to do so. Maybe some day it will break :)

**Comment by TomasVotruba** [comment]
> Yes I totally agree, that was the reason I started to write rector/phpstan rules for us to save time, because that situation I wrote about.

That's great! If you found any rule useful to the public, I'd love to merge it @rectorphp repo so millions of programmers hours can be saved :)

**Pull request merged**
