### PR TITLE
Update 2024-08-27-php-is-the-best-choice-for-long-term-business.md

### PR DESCRIPTION
**Pull request by ThomasLandauer**
This doesn't seem to be true - the next version will be 8.5 - not 9.0, according to https://php.watch/versions

### CODE REVIEW

**Comment by TomasVotruba** [comment]
What is the source for that? I could not find anything official

**Comment by ThomasLandauer** [comment]
Me neither :-(
But in 2 weeks, they will probably create a new branch for it here: https://github.com/php/php-src/branches - so you could just wait and see...

**Comment by TomasVotruba** [comment]
Indeed :+1:  

Let's see what future brings

**Comment by ThomasLandauer** [comment]
There is already 1 RFC for PHP 8.5: https://wiki.php.net/rfc/closures_in_const_expr
So it looks like this will be the next version.

**Comment by ThomasLandauer** [comment]
@TomasVotruba You should reopen and merge this; meanwhile it's official that the next version will be called 8.5: https://www.php.net/

**Pull request closed without merging**
