### PR TITLE
Fix typo and halt on error (#1392

### PR DESCRIPTION
**Pull request by szepeviktor**
Just those two.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Oops! `.env.local.dist` does not exist.

**Comment by szepeviktor** [comment]
Is it a production or development script?

**Comment by TomasVotruba** [comment]
Localhost :+1:

**Comment by TomasVotruba** [comment]
What is  `set -e` for?

**Comment by szepeviktor** [comment]
That tells Bash to halt on error.
Without `set -e` a failing `composer` or `yarn` command will be ignored, so the script keeps running.

**Comment by TomasVotruba** [comment]
I see. Could you drop a comment there so I won't forget next year?

**Comment by szepeviktor** [comment]
Yes.

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
