### PR TITLE
Update 2020-07-13-the-most-effetive-test-i-found-in-7-years-of-testing.md

### PR DESCRIPTION
**Pull request by vrbata**
Hi Tomáš,

nice post! I am sending you a few minor upgrades in this PR.

I think that `you don't maintainer to explain it` is not what you meant but I can't figure out the correct meaning so I can't change it. Also `The goal is to find what startup is different from other projects` doesn't seem right to me but it's above my level to improve it :D 

Thank you, looking forward to your next post already! :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi Pepa,

thank you again! You're such a care gives, it makes me write more and more just for you :D 

Any topic you'd be interested in?


I'll check the WTF sentence, thanks!

**Comment by TomasVotruba** [comment]
How does this sound?

https://github.com/TomasVotruba/tomasvotruba.com/commit/994dc0fc21d0714b3763b4c1401e613e1f6e2a84

**Comment by vrbata** [comment]
Nice, looks very good :)

I appreciate all the conversations we have had, I learned a lot. Also, we are using a lot of your open-source tools you have spent a lot of time on.
So I can spend a few minutes a weak to help improve such a good place to find out new things to learn and discover :)

I find some interesting ideas in almost every post so it's hard to tell but the power of AST for all sorts of automatizations from refactoring to automatic code reviews is something I am investigating now the most. Tools like rector and phpstan opened a huge door for me.

**Comment by TomasVotruba** [comment]
Much appreciated. I with there were more people like you in the world (not only open-source) :+1: :heart: 

If you ever need some free yet valuable consulting, just call :wink:

**Pull request merged**
